# Generated by Django 5.2.7 on 2025-12-12 08:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yayindan_kaldirilma_tarihi', models.DateField(blank=True, null=True, verbose_name='Yayından Kaldırılma Tarihi')),
                ('il', models.CharField(help_text='Zorunlu Alan. Örn: İstanbul, Kastamonu', max_length=50, verbose_name='İl (Şehir)')),
                ('ilce', models.CharField(help_text='Zorunlu Alan. Örn: Merkez, Beşiktaş', max_length=50, verbose_name='İlçe')),
                ('mahalle', models.CharField(help_text='Örn: Saraçlar Mh.', max_length=100, verbose_name='Mahalle/Semt')),
                ('adres', models.TextField(blank=True, help_text='Detaylı adres bilgisi (site içi, blok, kat vb.)', null=True, verbose_name='Açık Adres Detayı')),
                ('islem_tipi', models.CharField(choices=[('satilik', 'Satılık'), ('kiralik', 'Kiralık')], default='satilik', max_length=10, verbose_name='İşlem Tipi')),
                ('ilan_no', models.CharField(max_length=20, unique=True, verbose_name='İlan No')),
                ('baslik', models.CharField(max_length=150, verbose_name='İlan Başlığı')),
                ('ilan_tarihi', models.DateField(default=datetime.date.today, verbose_name='İlan Kayıt Tarihi')),
                ('ana_kategori', models.CharField(choices=[('konut', 'Konut'), ('isyeri', 'İş Yeri'), ('arsa', 'Arsa'), ('diger', 'Diğer')], default='konut', max_length=10, verbose_name='Mülk Tipi')),
                ('detay_kategori', models.CharField(choices=[('daire', 'Daire'), ('villa', 'Villa'), ('mustakil', 'Müstakil Ev'), ('dukkan', 'Dükkan'), ('ofis', 'Ofis'), ('depo', 'Depo'), ('tarla', 'Tarla'), ('bahce', 'Bahçe'), ('baska', 'Belirtilmemiş / Başka')], default='daire', max_length=10, verbose_name='Mülk Alt Tipi')),
                ('fiyat', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Fiyat')),
                ('brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Brüt Alan (m²)')),
                ('net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Alan (m²)')),
                ('oda_sayisi', models.CharField(choices=[('Stüdyo', '1+0 Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1 ve Üzeri'), ('6+', '6+ ve Daha Büyük'), ('Acik', 'Açık Alan'), ('1 Bölme', '1 Bölme'), ('2 Bölme', '2 Bölme'), ('3 Bölme', '3 Bölme'), ('4 Bölme', '4 Bölme'), ('5 Bölme', '5 Bölme ve Üzeri')], default='2+1', max_length=10, verbose_name='Oda Sayısı')),
                ('bina_yasi', models.IntegerField(blank=True, null=True, verbose_name='Bina Yaşı')),
                ('bulundugu_kat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bulunduğu Kat')),
                ('kat_sayisi', models.IntegerField(blank=True, null=True, verbose_name='Kat Sayısı')),
                ('isitma_tipi', models.CharField(choices=[('kombi', 'Kombi (Doğalgaz)'), ('merkezi', 'Merkezi Sistem'), ('payolcer', 'Merkezi (Pay Ölçer)'), ('klima', 'Klima'), ('soba', 'Soba/Katı Yakıt'), ('yok', 'Isıtma Yok/Diğer')], default='kombi', max_length=20, verbose_name='Isıtma Tipi')),
                ('banyo_sayisi', models.IntegerField(blank=True, null=True, verbose_name='Banyo Sayısı')),
                ('mutfak_tipi', models.CharField(choices=[('kapali', 'Kapalı Mutfak'), ('acik', 'Açık Mutfak (Amerikan)'), ('ayrilmis', 'Ayrılmış Mutfak'), ('yok', 'Mutfak Yok')], default='kapali', max_length=10, verbose_name='Mutfak Tipi')),
                ('balkon', models.BooleanField(default=False, verbose_name='Balkon')),
                ('asansor', models.BooleanField(default=False, verbose_name='Asansör')),
                ('otopark_durumu', models.CharField(choices=[('yok', 'Yok'), ('acik', 'Açık Otopark'), ('kapali', 'Kapalı Otopark'), ('acik_kapali', 'Açık ve Kapalı')], default='yok', max_length=15, verbose_name='Otopark Durumu')),
                ('esyali', models.BooleanField(default=False, verbose_name='Eşyalı')),
                ('kullanim_durumu', models.CharField(choices=[('boş', 'Boş'), ('oturuluyor', 'Oturuluyor'), ('kirada', 'Kirada'), ('tadilatta', 'Tadilatta')], default='Boş', max_length=50, verbose_name='Kullanım Durumu')),
                ('site_icerisinde', models.BooleanField(default=False, verbose_name='Site İçerisinde')),
                ('site_adi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Adı')),
                ('aidat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aidat')),
                ('krediye_uygun', models.BooleanField(default=False, verbose_name='Krediye Uygun')),
                ('tapu_durumu', models.CharField(choices=[('kat_mulkiyeti', 'Kat Mülkiyeti'), ('kat_irtifaki', 'Kat İrtifakı'), ('hisseli', 'Hisseli Tapu'), ('mustakil', 'Müstakil Tapu (Arsa)'), ('tahsis', 'Tahsis')], default='kat_mulkiyeti', max_length=20, verbose_name='Tapu Durumu (Mülkiyet)')),
                ('kimden', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlan Sahibi')),
                ('takas', models.BooleanField(default=False, verbose_name='Takas')),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=20, verbose_name='Durum')),
                ('pasif_nedeni', models.CharField(blank=True, choices=[('Satildi', 'Satıldı'), ('Kiralandi', 'Kiralandı'), ('Kadirildi', 'Kullanıcı Tarafından Kaldırıldı')], max_length=50, null=True, verbose_name='Pasif Nedeni')),
                ('imar_durumu', models.CharField(choices=[('konut_imari', 'Konut İmarlı'), ('ticari_imari', 'Ticari İmarlı'), ('sanayi_imari', 'Sanayi İmarlı'), ('tarim', 'Tarım/Ziraat Alanı'), ('imar_yok', 'İmar Yok'), ('karma', 'Karma Kullanım')], default='imar_yok', max_length=20, verbose_name='İmar Durumu')),
                ('m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alan (m²)')),
                ('m2_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='m² Fiyatı')),
                ('ada_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ada No')),
                ('parsel_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parsel No')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar', to='ilanlar.musteri', verbose_name='İlan Sahibi')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-ilan_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='PotansiyelMusteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('telefon', models.CharField(max_length=20, unique=True, verbose_name='Telefon Numarası')),
                ('ilgili_ilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='ilanlar.ilan', verbose_name='İlgili İlan')),
            ],
            options={
                'verbose_name': 'Potansiyel Müşteri',
                'verbose_name_plural': 'Potansiyel Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih_saat', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Randevu Tarihi ve Saati')),
                ('durum', models.CharField(choices=[('PLAN', 'Planlandı'), ('TAMAM', 'Tamamlandı'), ('IPTAL', 'İptal Edildi')], default='PLAN', max_length=5, verbose_name='Durum')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Ek Notlar/Detaylar')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='ilanlar.ilan', verbose_name='İlgili İlan')),
                ('potansiyel_musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='ilanlar.potansiyelmusteri', verbose_name='Randevu Alan Kişi')),
            ],
        ),
    ]
