# Generated by Django 5.2.7 on 2025-11-21 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='ilan_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='İlan Kayıt Tarihi'),
        ),
    ]
