# Generated by Django 5.2.7 on 2025-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0002_alter_randevu_options_alter_ilan_brut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='detay_kategori',
            field=models.CharField(choices=[('daire', 'Daire'), ('villa', 'Villa'), ('mustakil', 'Müstakil Ev'), ('dukkan', 'Dükkan'), ('ofis', 'Ofis'), ('fabrika', 'Fabrika'), ('depo', 'Depo'), ('tarla', 'Tarla'), ('bahce', 'Bahçe'), ('baska', 'Belirtilmemiş / Başka')], default='daire', max_length=10, verbose_name='Mülk Alt Tipi'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='pasif_nedeni',
            field=models.CharField(blank=True, choices=[('Satildi', 'Satıldı'), ('Kiralandi', 'Kiralandı'), ('Yayin_Suresi_Bitti', 'Yayın Süresi Bitti'), ('Kadirildi', 'Kullanıcı Tarafından Kaldırıldı')], max_length=50, null=True, verbose_name='Pasif Nedeni'),
        ),
    ]
