# Generated by Django 5.2.7 on 2025-11-21 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0002_ilan_ilan_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='ilan_tarihi',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='İlan Kayıt Tarihi'),
        ),
    ]
