# Generated by Django 5.2.7 on 2025-12-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0003_alter_ilan_detay_kategori_alter_ilan_pasif_nedeni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(verbose_name='Görev Tarihi ve Saati')),
                ('oncelik', models.CharField(choices=[('1', 'Düşük'), ('2', 'Orta'), ('3', 'Yüksek')], default='2', max_length=1, verbose_name='Öncelik')),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Tamamlandi', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Bekliyor', max_length=20, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Ajanda / Görevler',
                'ordering': ['tarih'],
            },
        ),
    ]
