# Generated by Django 5.2.7 on 2025-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0003_alter_ilan_ilan_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='ana_kategori',
            field=models.CharField(choices=[('konut', 'Konut'), ('isyeri', 'İş Yeri'), ('arsa', 'Arsa'), ('diger', 'Diğer')], default='konut', max_length=10, verbose_name='Mülk Tipi(Ana Kategori)'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='detay_kategori',
            field=models.CharField(choices=[('daire', 'Daire'), ('villa', 'Villa'), ('mustakil', 'Müstakil Ev'), ('dukkan', 'Dükkan'), ('ofis', 'Ofis'), ('depo', 'Depo'), ('tarla', 'Tarla'), ('bahce', 'Bahçe'), ('baska', 'Belirtilmemiş / Başka')], default='daire', max_length=10, verbose_name='Mülk Alt Tipi'),
        ),
    ]
