# Generated by Django 5.2.7 on 2025-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0004_ajanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fiyat'),
        ),
    ]
