# Generated by Django 5.2.7 on 2025-11-22 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0004_ilan_ana_kategori_ilan_detay_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='ilan_tarihi',
            field=models.DateField(default=datetime.date.today, verbose_name='İlan Kayıt Tarihi'),
        ),
    ]
