# Generated by Django 5.2.7 on 2025-11-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0005_alter_ilan_ilan_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='ana_kategori',
            field=models.CharField(choices=[('konut', 'Konut'), ('isyeri', 'İş Yeri'), ('arsa', 'Arsa'), ('diger', 'Diğer')], default='konut', max_length=10, verbose_name='Mülk Tipi'),
        ),
    ]
