# Generated by Django 5.2.7 on 2025-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0006_alter_ilan_ana_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilan',
            options={'ordering': ['-ilan_tarihi'], 'verbose_name': 'İlan', 'verbose_name_plural': 'İlanlar'},
        ),
        migrations.AddField(
            model_name='ilan',
            name='durum',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Fiyat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='oda_sayisi',
            field=models.CharField(default=1, max_length=10, verbose_name='Oda Sayısı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilan',
            name='ana_kategori',
            field=models.CharField(choices=[('konut', 'Konut'), ('isyeri', 'İş Yeri'), ('arsa', 'Arsa'), ('diger', 'Diğer')], default='konut', max_length=10, verbose_name='Mülk Tipi (Ana Kategori)'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='baslik',
            field=models.CharField(max_length=150, verbose_name='İlan Başlığı'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='ilan_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='İlan No'),
        ),
    ]
