# Generated by Django 5.2.7 on 2025-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0007_alter_ilan_options_ilan_durum_ilan_fiyat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='aidat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aidat'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='asansor',
            field=models.BooleanField(default=False, verbose_name='Asansör'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='balkon',
            field=models.BooleanField(default=False, verbose_name='Balkon'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='banyo_sayisi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Banyo Sayısı'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='bina_yasi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bina Yaşı'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='brut',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Brüt Alan (m²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='bulundugu_kat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Bulunduğu Kat'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='esyali',
            field=models.BooleanField(default=False, verbose_name='Eşyalı'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='isitma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Isıtma Tipi'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='kat_sayisi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kat Sayısı'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='kimden',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlan Sahibi'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='krediye_uygun',
            field=models.BooleanField(default=False, verbose_name='Krediye Uygun'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='kullanim_durumu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanım Durumu'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='mutfak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mutfak Tipi'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Alan (m²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='otopark',
            field=models.BooleanField(default=False, verbose_name='Otopark'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='site_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Adı'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='site_icerisinde',
            field=models.BooleanField(default=False, verbose_name='Site İçerisinde'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='takas',
            field=models.BooleanField(default=False, verbose_name='Takas'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='tapu_durumu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tapu Durumu'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='ana_kategori',
            field=models.CharField(choices=[('konut', 'Konut'), ('isyeri', 'İş Yeri'), ('arsa', 'Arsa'), ('diger', 'Diğer')], default='konut', max_length=10, verbose_name='Mülk Tipi'),
        ),
    ]
