# Generated by Django 5.2.7 on 2025-11-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0008_ilan_aidat_ilan_asansor_ilan_balkon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='ada_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ada No'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='imar_durumu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İmar Durumu'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alan (m²)'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='m2_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='m² Fiyatı'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='parsel_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parsel No'),
        ),
    ]
