# Generated by Django 5.2.7 on 2025-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0009_ilan_ada_no_ilan_imar_durumu_ilan_m2_ilan_m2_fiyati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='imar_durumu',
            field=models.CharField(choices=[('konut_imari', 'Konut İmarlı'), ('ticari_imari', 'Ticari İmarlı'), ('sanayi_imari', 'Sanayi İmarlı'), ('tarim', 'Tarım/Ziraat Alanı'), ('imar_yok', 'İmar Yok'), ('karma', 'Karma Kullanım')], default='imar_yok', max_length=20, verbose_name='İmar Durumu'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='isitma',
            field=models.CharField(choices=[('kombi', 'Kombi (Doğalgaz)'), ('merkezi', 'Merkezi Sistem'), ('payolcer', 'Merkezi (Pay Ölçer)'), ('klima', 'Klima'), ('soba', 'Soba/Katı Yakıt'), ('yok', 'Isıtma Yok/Diğer')], default='kombi', max_length=20, verbose_name='Isıtma Tipi'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='mutfak',
            field=models.CharField(choices=[('kapali', 'Kapalı Mutfak'), ('acik', 'Açık Mutfak (Amerikan)'), ('ayrilmis', 'Ayrılmış Mutfak'), ('yok', 'Mutfak Yok')], default='kapali', max_length=10, verbose_name='Mutfak Tipi'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='oda_sayisi',
            field=models.CharField(choices=[('Stüdyo', '1+0 Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1 ve Üzeri'), ('6+', '6+ ve Daha Büyük'), ('Acik', 'Açık Konsept')], default='2+1', max_length=10, verbose_name='Oda Sayısı'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='otopark',
            field=models.CharField(choices=[('yok', 'Yok'), ('acik', 'Açık Otopark'), ('kapali', 'Kapalı Otopark'), ('acik_kapali', 'Açık ve Kapalı')], default='yok', max_length=15, verbose_name='Otopark Durumu'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='tapu_durumu',
            field=models.CharField(choices=[('kat_mulkiyeti', 'Kat Mülkiyeti'), ('kat_irtifaki', 'Kat İrtifakı'), ('hisseli', 'Hisseli Tapu'), ('mustakil', 'Müstakil Tapu (Arsa)'), ('tahsis', 'Tahsis')], default='kat_mulkiyeti', max_length=20, verbose_name='Tapu Durumu (Mülkiyet)'),
        ),
    ]
