# Generated by Django 5.2.7 on 2025-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0010_alter_ilan_imar_durumu_alter_ilan_isitma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='imar_durumu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İmar Durumu'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='isitma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Isıtma Tipi'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='mutfak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mutfak Tipi'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='oda_sayisi',
            field=models.CharField(max_length=10, verbose_name='Oda Sayısı'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='otopark',
            field=models.BooleanField(default=False, verbose_name='Otopark'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='tapu_durumu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tapu Durumu'),
        ),
    ]
