# Generated by Django 5.2.7 on 2025-11-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0011_alter_ilan_imar_durumu_alter_ilan_isitma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilan',
            name='isitma',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='mutfak',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='otopark',
        ),
        migrations.AddField(
            model_name='ilan',
            name='isitma_tipi',
            field=models.CharField(choices=[('kombi', 'Kombi (Doğalgaz)'), ('merkezi', 'Merkezi Sistem'), ('payolcer', 'Merkezi (Pay Ölçer)'), ('klima', 'Klima'), ('soba', 'Soba/Katı Yakıt'), ('yok', 'Isıtma Yok/Diğer')], default='kombi', max_length=20, verbose_name='Isıtma Tipi'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='mutfak_tipi',
            field=models.CharField(choices=[('kapali', 'Kapalı Mutfak'), ('acik', 'Açık Mutfak (Amerikan)'), ('ayrilmis', 'Ayrılmış Mutfak'), ('yok', 'Mutfak Yok')], default='kapali', max_length=10, verbose_name='Mutfak Tipi'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='otopark_durumu',
            field=models.CharField(choices=[('yok', 'Yok'), ('acik', 'Açık Otopark'), ('kapali', 'Kapalı Otopark'), ('acik_kapali', 'Açık ve Kapalı')], default='yok', max_length=15, verbose_name='Otopark Durumu'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='oda_sayisi',
            field=models.CharField(choices=[('Stüdyo', '1+0 Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1 ve Üzeri'), ('6+', '6+ ve Daha Büyük'), ('Acik', 'Açık Konsept')], default='2+1', max_length=10, verbose_name='Oda Sayısı'),
        ),
    ]
