# Generated by Django 5.2.7 on 2025-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0012_remove_ilan_isitma_remove_ilan_mutfak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='imar_durumu',
            field=models.CharField(choices=[('konut_imari', 'Konut İmarlı'), ('ticari_imari', 'Ticari İmarlı'), ('sanayi_imari', 'Sanayi İmarlı'), ('tarim', 'Tarım/Ziraat Alanı'), ('imar_yok', 'İmar Yok'), ('karma', 'Karma Kullanım')], default='imar_yok', max_length=20, verbose_name='İmar Durumu'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='tapu_durumu',
            field=models.CharField(choices=[('kat_mulkiyeti', 'Kat Mülkiyeti'), ('kat_irtifaki', 'Kat İrtifakı'), ('hisseli', 'Hisseli Tapu'), ('mustakil', 'Müstakil Tapu (Arsa)'), ('tahsis', 'Tahsis')], default='kat_mulkiyeti', max_length=20, verbose_name='Tapu Durumu (Mülkiyet)'),
        ),
    ]
