# Generated by Django 5.2.7 on 2025-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0013_alter_ilan_imar_durumu_alter_ilan_tapu_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='islem_tipi',
            field=models.CharField(choices=[('satilik', 'Satılık'), ('kiralik', 'Kiralık')], default='satilik', max_length=10, verbose_name='İşlem Tipi'),
        ),
    ]
