# Generated by Django 5.2.7 on 2025-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0014_ilan_islem_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='adres',
            field=models.TextField(blank=True, help_text='Detaylı adres bilgisi (site içi, blok, kat vb.)', null=True, verbose_name='Açık Adres Detayı'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='il',
            field=models.CharField(default=1, help_text='Zorunlu Alan. Örn: İstanbul, Kastamonu', max_length=50, verbose_name='İl (Şehir)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='ilce',
            field=models.CharField(default=11, help_text='Zorunlu Alan. Örn: Merkez, Beşiktaş', max_length=50, verbose_name='İlçe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='mahalle',
            field=models.CharField(default=1, help_text='Örn: Saraçlar Mh.', max_length=100, verbose_name='Mahalle/Semt'),
            preserve_default=False,
        ),
    ]
