# Generated by Django 5.2.7 on 2025-12-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0016_musteri'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar', to='ilanlar.musteri', verbose_name='İlan Sahibi'),
        ),
    ]
