# Generated by Django 5.2.7 on 2025-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0017_ilan_musteri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='kullanim_durumu',
            field=models.CharField(choices=[('boş', 'Boş'), ('oturuluyor', 'Oturuluyor'), ('kirada', 'Kirada'), ('tadilatta', 'Tadilatta')], default='Boş', max_length=50, verbose_name='Kullanım Durumu'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='oda_sayisi',
            field=models.CharField(choices=[('Stüdyo', '1+0 Stüdyo'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1 ve Üzeri'), ('6+', '6+ ve Daha Büyük'), ('Acik', 'Açık Alan'), ('1 Bölme', '1 Bölme'), ('2 Bölme', '2 Bölme'), ('3 Bölme', '3 Bölme'), ('4 Bölme', '4 Bölme'), ('5 Bölme', '5 Bölme ve Üzeri')], default='2+1', max_length=10, verbose_name='Oda Sayısı'),
        ),
    ]
