# Generated by Django 5.2.7 on 2025-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0018_alter_ilan_kullanim_durumu_alter_ilan_oda_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='yayindan_kaldirilma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayından Kaldırılma Tarihi'),
        ),
    ]
