# Generated by Django 5.2.7 on 2025-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0019_ilan_yayindan_kaldirilma_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='fiyat',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='yayindan_kaldirilma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Yayından Kaldırılma Tarihi'),
        ),
    ]
