# Generated by Django 5.2.7 on 2025-12-02 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0020_alter_ilan_fiyat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih_saat', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Randevu Tarihi ve Saati')),
                ('durum', models.CharField(choices=[('PLAN', 'Planlandı'), ('TAMAM', 'Tamamlandı'), ('IPTAL', 'İptal Edildi')], default='PLAN', max_length=5)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='ilanlar.ilan', verbose_name='İlgili İlan')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevu_talepleri', to='ilanlar.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
            },
        ),
    ]
