# Generated by Django 5.2.7 on 2025-12-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0021_randevu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='musteri',
        ),
        migrations.AddField(
            model_name='randevu',
            name='ad',
            field=models.CharField(default=1, max_length=100, verbose_name='Ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randevu',
            name='soyad',
            field=models.CharField(default=1, max_length=100, verbose_name='Soyad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randevu',
            name='telefon',
            field=models.CharField(default=0, max_length=20, verbose_name='Telefon'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PotansiyelMusteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20, unique=True)),
                ('ilgili_ilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='ilanlar.ilan')),
            ],
            options={
                'verbose_name': 'Potansiyel Müşteri',
            },
        ),
    ]
