# Generated by Django 5.2.7 on 2025-12-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0022_remove_randevu_musteri_randevu_ad_randevu_soyad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Ek Notlar/Detaylar'),
        ),
    ]
