# Generated by Django 5.2.7 on 2025-12-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0023_randevu_notlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potansiyelmusteri',
            options={'verbose_name': 'Potansiyel Müşteri', 'verbose_name_plural': 'Potansiyel Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='randevu',
            options={},
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='soyad',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='telefon',
        ),
        migrations.AddField(
            model_name='randevu',
            name='potansiyel_musteri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='ilanlar.potansiyelmusteri', verbose_name='Randevu Alan Kişi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potansiyelmusteri',
            name='ad',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='potansiyelmusteri',
            name='ilgili_ilan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='ilanlar.ilan', verbose_name='İlgili İlan'),
        ),
        migrations.AlterField(
            model_name='potansiyelmusteri',
            name='soyad',
            field=models.CharField(max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='potansiyelmusteri',
            name='telefon',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='durum',
            field=models.CharField(choices=[('PLAN', 'Planlandı'), ('TAMAM', 'Tamamlandı'), ('IPTAL', 'İptal Edildi')], default='PLAN', max_length=5, verbose_name='Durum'),
        ),
    ]
